### ISSUE TITLE
Criação de Banco de Dados

### ISSUE THREAD

**Issue by JanRocha** [FabricaAppU9/EcoLoc#10]

**Comment by Andre-VGoncalves** [comment]
Este script está no driver.

CREATE TABLE UsuarioDTO(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(50) NOT NULL,
  senha VARCHAR(30) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Pontos (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL,
  latitude VARCHAR(30) NOT NULL,
  longitude VARCHAR(30) NOT NULL,
  PRIMARY KEY(idPonto)
);

CREATE TABLE Ranking (
  idUsuario NOT NULL AUTO_INCREMENT,
  pontuacao INTEGER UNSIGNED NOT NULL,
  CONSTRAINT fk_usuario_Ranking FOREIGN KEY(idUsuario) references Usuarios(id) 
);
