### ISSUE TITLE
Revisão do Modelo de Dados

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLoc#15]

**Comment by GolfettoGuilherme** [comment]
https://drive.google.com/drive/folders/0B-Duok-wdhp3RHVEZ2MxQXd3UkU?usp=sharing

**Comment by JanRocha** [comment]
Revisado a documentação para a versão 1.8, acrescentado alguns casos de uso e corrido alguns, criado o dicionario de dados, detalhado superficialmente o Web Service.
