### ISSUE TITLE
Implementar Retrofit 2.0 no Android

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLoc#16]
E o dialogo de primeiros passos.

**Comment by JanRocha** [comment]
Retrofit atualizado, para a versão 2.4.0 e implementado a atualização da biblioteca Gson.
link que utilizei para me orientar: [https://www.youtube.com/watch?v=nFIvV5_QTOE]

**Comment by JanRocha** [comment]
Implementado Retrofit 2.0
