### ISSUE TITLE
Estudar Android

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLoc#18]
Incluir Links de acesso aqui

**Comment by GolfettoGuilherme** [comment]
https://drive.google.com/drive/folders/0Bx5VppDMoe4UTEwwV3ZpZXFmdUU?usp=sharing

**Comment by JulioMCDias** [comment]
https://drive.google.com/drive/folders/0B9O2UElES04RMTQ4eXN6YzIxQmM?usp=sharing

**Comment by Andre-VGoncalves** [comment]
Gosto desse canal (esta em ingles)

primeiro curso deles
desenvolvimento android
https://www.youtube.com/watch?v=hzrGAZnMOMQ&list=PLonJJ3BVjZW6hYgvtkaWvwAVvOFB7fkLa

curso de design para android
https://www.youtube.com/watch?v=h57QpXp2TRg&list=PLonJJ3BVjZW6CtAMbJz1XD8ELUs1KXaTD

**Comment by Andre-VGoncalves** [comment]
Não é só para android 
mas tem varios tutorias maneiros e explicações
