### ISSUE TITLE
Estudar Git

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLoc#19]

**Comment by GolfettoGuilherme** [comment]
http://rogerdudler.github.io/git-guide/index.pt_BR.html

**Comment by Andre-VGoncalves** [comment]
-----comandos mais utlizados no dia dia-----

git status
git add .
git commit -m "descricao"
git push origin <branch>

---- descrição dos comandos -----

git status -verifica em quais arquivos voce mexeu e podem ser commitados

git add <nome do arquivo> - adciona um elemento para ser commitado
git add .java - adciona todos arquivos com extensão java podendo variar de acordo com a extensão que voce queira
git add . -adciona todos arquivos para commit ignorando os arquivos que esta no git ignore

git commit -m "descrição do que fez aqui" -adciona as mudanças no repositorio local

git push origin <branch> -sobe o seu repositorio local para o repositorio na nuvem github gitlab bit

git pull -atualiza seu repositorio local com o que esta na branch que esta trabalhando
git pull origin <branch> -atualiza seu repositorio com a branch que de sua escolha

git checkout <branch> -muda de branch
git checkout -b <nome de sua escolha> - cria uma branch no repositorio local
git checkout -- . -remove todos arquivos editados para não serem adcionado ao commit

git merge <branch> -junta uma branch com outra voce sempre tem que esta na branch que quer que seja atualizada
//caso de conflito normalmente as IDE ajuda a resolver o androidStudio sei que ajuda

git fetch -pusa para o repositorio local todas as branch que esta no repositorio do github

git stash -caso tenha feito na branch errada ele consegue pegar tudo que fez e salvar no seu repositorio local para voce transferir para branch correta
git stash apply -pega os dados que foi salvo com stash e adciona na branch de sua escolha // se fez o commit não tem como fazer o stash

**Comment by JanRocha** [comment]
testado os comandos, ok.
