### ISSUE TITLE
Estudo de implementação de Interfaces

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLoc#6]

**Comment by MateusGuedess** [comment]
Fiz uma busca por menus em baixo e achei uma biblioteca fácil e simples de usar chamada BottomBar.
Essa Biblioteca oferece também outras perfumarias como: mudar icone quando selecionado, esconder menu quando der Scroll, cores, badges ou notificações e etc. 

https://github.com/roughike/BottomBar

**Comment by GolfettoGuilherme** [comment]
ok
